services:
  laravel:
    image: i-chunk-laravel:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_VERSION: "${IMAGE_VERSION}"
        LARAVEL_VERSION: "${LARAVEL_VERSION}"
    command: php /app/${LARAVEL_VERSION}/artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
